version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE=short
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_HOST=localhost
      - DB_PORT=5432
      - DIALECT=postgres
    depends_on:
      - db
  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=short

volumes:
  postgres_data: