version: '3.8'

services:

  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: node:20
    container_name: app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    command: ["npm", "run", "start:p"]